name: bifrost
description: Bifrost
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  logging:
  async:
  integral_isolates: ^0.3.0+2
  bifrost_blockchain:
    path: ../blockchain
  bifrost_codecs:
    path: ../codecs
  bifrost_crypto:
    path: ../crypto
  topl_protobuf:
    path: ../../protobuf-specs/build/dart
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
