name: quivr
description: Quivr

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'


dependencies:
  hashlib:
  collection:
  fixnum:
  topl_protobuf:
    path: ../../protobuf-specs/build/dart
dev_dependencies:    
  build_runner: ^2.3.3
