name: bifrost_consensus
description: Bifrost Consensus

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'


dependencies:
  fpdart: ^0.3.0
  rational: ^2.2.2
  hashlib: ^1.8.1
  logging:
  fixnum:
  topl_protobuf:
    path: ../../protobuf-specs/build/dart
  bifrost_codecs:
    path: ../codecs
  bifrost_common:
    path: ../common
  bifrost_crypto:
    path: ../crypto
dev_dependencies:    
  build_runner: ^2.3.3
  test:
  convert: ^3.1.1
